import { Disclosure } from "@headlessui/react";
import { MenuAlt1Icon, XIcon } from "@heroicons/react/outline";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { type NextPage } from "next";
import Head from "next/head";

import dynamic from "next/dynamic";
dayjs.extend(relativeTime);

const MainView = dynamic(() => import("../views/Main"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Screen Recorder</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="fixed top-0 left-0 h-full w-1/2 " aria-hidden="true" />
        <div className="fixed top-0 right-0 h-full w-1/2 " aria-hidden="true" />
        <div className="relative flex min-h-screen flex-col">
          <Disclosure as="nav" className="flex-shrink-0 bg-secondary">
            {({ open }) => (
              <>
                <div className="mx-auto max-w-7xl px-2 sm:px-4 lg:px-8">
                  <div className="relative flex h-16 items-center justify-between">
                    <div className="flex items-center px-2 lg:px-0 xl:w-64">
                      <div className="flex-shrink-0"></div>
                    </div>

                    <div className="flex lg:hidden">
                      <Disclosure.Button className="btn-primary btn">
                        <span className="sr-only">Open main menu</span>
                        {open ? (
                          <XIcon className="block h-6 w-6" aria-hidden="true" />
                        ) : (
                          <MenuAlt1Icon
                            className="block h-6 w-6"
                            aria-hidden="true"
                          />
                        )}
                      </Disclosure.Button>
                    </div>
                    <div className="hidden lg:block lg:w-80">
                      <div className="flex items-center justify-end">
                        <div className="flex">
                          <a href="#" className="btn-primary btn rounded-md ">
                            Features Coming Soon
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <Disclosure.Panel className="lg:hidden">
                  <div className="px-2 pt-2 pb-3">
                    <Disclosure.Button
                      as="a"
                      href="#"
                      className="block rounded-md bg-indigo-800 px-3 py-2 text-base font-medium text-white"
                    >
                      Coming Soon
                    </Disclosure.Button>
                  </div>
                </Disclosure.Panel>
              </>
            )}
          </Disclosure>
          <div className="mx-auto w-full max-w-7xl flex-grow lg:flex xl:px-8">
            <MainView />
          </div>
        </div>
      </>
    </>
  );
};

export default Home;
